/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 node-transformed.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['tripo_node_a2ae1f0a-576e-4d11-a22b-f4f90dd99b4b']: THREE.Mesh
  }
  materials: {
    ['tripo_material_a2ae1f0a-576e-4d11-a22b-f4f90dd99b4b']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/node-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_a2ae1f0a-576e-4d11-a22b-f4f90dd99b4b'].geometry} material={materials['tripo_material_a2ae1f0a-576e-4d11-a22b-f4f90dd99b4b']} />
    </group>
  )
}

useGLTF.preload('/node-transformed.glb')
