/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 python-transformed.glb --types 
Author: Acvantad (https://sketchfab.com/Acvantad)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/python-programming-language-44d992bf56e244448e9ee5b4da083287
Title: Python Programming language
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
    ['.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/python-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material} position={[-0.002, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={2.501} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['.001']} position={[-0.002, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={2.501} />
    </group>
  )
}

useGLTF.preload('/python-transformed.glb')
