/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bumblebee.glb --types 
Author: Pipogame (https://sketchfab.com/joseclaudio162001)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tf-alliance-bumblebee-2007-rotf-5c695a9da1664cc1bbf9a1646e59f03b
Title: TF Alliance Bumblebee 2007 ROTF
*/

import * as THREE from 'three'
import React, { useEffect, useState, useMemo, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Bumblebee(props) {
    const group = useRef(null)
    const { scene, animations } = useGLTF('/models/bumblebee.glb')
    const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
    const { nodes, materials } = useGraph(clone)
    const { actions } = useAnimations(animations, group)

    const [index, setIndex] = useState(0)
    const allActions = ['vehicle_idle01', 'idle01', 'emo_joyful', 'emo_rage', 'emo_sad', 'emo_stagger', 'emo_surprise', 'dash']

    // Cycle animations every 3 seconds
    useEffect(() => {
        const interval = setInterval(() => {
            setIndex((prev) => (prev + 1) % allActions.length)
        }, 3000)
        return () => clearInterval(interval)
    }, [allActions.length])

    useEffect(() => {
        // Play new action - either from props or the cycled index
        const actionName = props.action || allActions[index]
        const action = actions[actionName]

        if (action) {
            action.reset().fadeIn(0.5).play()
            return () => {
                action.fadeOut(0.5)
            }
        }
    }, [actions, props.action, index])


    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={118.279}>
                    <group name="BumbleBee_2007_ROTF_pbrfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="BumbleBee_MV1_pbr">
                                    <group name="BumbleBee_MV1">
                                        <group name="Object_6">
                                            <primitive object={nodes._rootJoint} />
                                            <group name="Object_8" rotation={[-Math.PI / 2, 0, 0]} />
                                            <group name="BumbleBee_MV1_1" rotation={[-Math.PI / 2, 0, 0]} />
                                            <group name="Shadow" scale={1.566} />
                                            <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.M_BumbleBee_MV1} skeleton={nodes.Object_9.skeleton} />
                                        </group>
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/bumblebee.glb')
